### PR TITLE
Mutable default parameters is not a bug

### PR DESCRIPTION
**Pull request by Rosuav**
It is something to be aware of, but there's no need to panic people.

### CODE REVIEW

**Comment by NDevox** [comment]
More to the point, is None really something that should be enforced as default?

**Comment by Rosuav** [comment]
Well, if you want a new list every time, None works fine. If you want to accept any arbitrary object, you need a unique object() sentinel. For a simple list like this, None makes a perfectly good example.

**Comment by NDevox** [comment]
I can agree with it if you want a new list every time. But the header is simply "use None as default parameter". Which to me suggests you should never use anything else.

**Comment by Rosuav** [comment]
I didn't want to do overly wholesale edits, so I just removed the "Always". But really, this topic is too broad for a simple list of snippets.

**Pull request merged**
